# Builds the plugin and installs it into the BepInEx folder Rai Pal uses for Liftoff.
#
# Needs no .NET SDK: it uses csc.exe from the .NET Framework that ships with Windows.
# That compiler only speaks C# 5, so no nameof, no string interpolation, no ?. operator.
# See LiftoffFpvGoggles.csproj for the .NET SDK route, which gives modern C# and IntelliSense.
#
# Paths are detected automatically. Override them if the detection fails:
#   .\build.ps1 -GameDir "D:\Games\Liftoff Micro Drones" -BepInExDir "C:\...\bepinex\BepInEx"

param(
    [string]$GameDir,
    [string]$BepInExDir,
    [switch]$NoInstall
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $MyInvocation.MyCommand.Path

# ---------------------------------------------------------------- game folder

function Find-GameDir {
    $steam = (Get-ItemProperty "HKCU:\Software\Valve\Steam" -ErrorAction SilentlyContinue).SteamPath
    if (-not $steam) { $steam = "C:\Program Files (x86)\Steam" }

    $libraries = @($steam)
    $vdf = Join-Path $steam "steamapps\libraryfolders.vdf"
    if (Test-Path $vdf) {
        Select-String -Path $vdf -Pattern '"path"\s+"(.+?)"' | ForEach-Object {
            $libraries += $_.Matches[0].Groups[1].Value -replace '\\\\', '\'
        }
    }

    foreach ($library in ($libraries | Select-Object -Unique)) {
        $candidate = Join-Path $library "steamapps\common\Liftoff Micro Drones"
        if (Test-Path (Join-Path $candidate "Liftoff Micro Drones_Data\Managed")) { return $candidate }
    }
    return $null
}

if (-not $GameDir) { $GameDir = Find-GameDir }
if (-not $GameDir) {
    throw "Liftoff not found. Pass it explicitly: .\build.ps1 -GameDir ""<path to Liftoff Micro Drones>"""
}

$managed = Join-Path $GameDir "Liftoff Micro Drones_Data\Managed"
if (-not (Test-Path $managed)) { throw "Not a Liftoff install (no Managed folder): $GameDir" }

# ---------------------------------------------------------------- BepInEx folder

function Find-BepInExDir {
    $modsRoot = Join-Path $env:APPDATA "raicuparta\rai-pal\data\installed-mods"
    if (-not (Test-Path $modsRoot)) { return $null }

    # Rai Pal keys folders by game id, so pick the one that actually has UUVR in it.
    foreach ($dir in (Get-ChildItem $modsRoot -Directory)) {
        $candidate = Join-Path $dir.FullName "bepinex\BepInEx"
        if (Test-Path (Join-Path $candidate "plugins\uuvr-mono-modern")) { return $candidate }
    }
    return $null
}

# Detected even with -NoInstall: BepInEx.dll and 0Harmony.dll are needed to compile at all.
if (-not $BepInExDir) { $BepInExDir = Find-BepInExDir }

# ---------------------------------------------------------------- compile

$outDir = Join-Path $root "build"
$outDll = Join-Path $outDir "LiftoffFpvGoggles.dll"
$csc = "$env:WINDIR\Microsoft.NET\Framework64\v4.0.30319\csc.exe"

if (-not (Test-Path $csc)) { throw "C# compiler not found: $csc" }
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }

# Built against the game's own assemblies (.NET Standard 2.1), not the compiler's framework -
# hence /nostdlib+ together with Unity's mscorlib and netstandard. Without this the build
# fails with "CS0012: System.Object ... netstandard 2.1".
$refs = @(
    "$managed\mscorlib.dll",
    "$managed\netstandard.dll",
    "$managed\UnityEngine.dll",
    "$managed\UnityEngine.CoreModule.dll",
    "$managed\UnityEngine.UIModule.dll",
    "$managed\UnityEngine.XRModule.dll",
    "$managed\UnityEngine.VRModule.dll"   # XRSettings lives here, not in XRModule
)

if ($BepInExDir) {
    $refs += "$BepInExDir\core\BepInEx.dll"
    $refs += "$BepInExDir\core\0Harmony.dll"
} else {
    # Allow building without Rai Pal by dropping BepInEx.dll and 0Harmony.dll into lib\.
    $refs += (Join-Path $root "lib\BepInEx.dll")
    $refs += (Join-Path $root "lib\0Harmony.dll")
}

foreach ($r in $refs) {
    if (-not (Test-Path $r)) { throw "Missing reference: $r" }
}

$sources = Get-ChildItem (Join-Path $root "src") -Filter *.cs -Recurse | ForEach-Object { $_.FullName }
if (-not $sources) { throw "No sources found in $root\src" }

# Hand the detected paths to the csproj, so "dotnet build" and IntelliSense work too without
# anyone's machine specific paths ending up in version control.
$localProps = @"
<Project>
  <!-- Generated by build.ps1. Not in version control. -->
  <PropertyGroup>
    <GameManaged>$managed</GameManaged>
    <BepInExDir>$BepInExDir</BepInExDir>
  </PropertyGroup>
</Project>
"@
Set-Content -Path (Join-Path $root "Local.props") -Value $localProps -Encoding UTF8

$cscArgs = @("/nologo", "/target:library", "/optimize+", "/warn:4", "/nostdlib+", "/out:$outDll")
$cscArgs += ($refs | ForEach-Object { "/reference:$_" })
$cscArgs += $sources

Write-Host "Game:    $GameDir" -ForegroundColor DarkGray
Write-Host "BepInEx: $(if ($BepInExDir) { $BepInExDir } else { '(lib\ fallback)' })" -ForegroundColor DarkGray
Write-Host "Compiling..." -ForegroundColor Cyan

& $csc $cscArgs
if ($LASTEXITCODE -ne 0) { throw "Compilation failed (exit $LASTEXITCODE)" }

if ($NoInstall -or -not $BepInExDir) {
    Write-Host "OK -> $outDll" -ForegroundColor Green
    return
}

# ---------------------------------------------------------------- install

$pluginDir = Join-Path $BepInExDir "plugins\LiftoffFpvGoggles"
if (-not (Test-Path $pluginDir)) { New-Item -ItemType Directory -Path $pluginDir -Force | Out-Null }

# While the game runs it holds the DLL open. That is not a build failure - the compiled
# assembly is in build\ and gets copied on the next run.
try {
    Copy-Item $outDll $pluginDir -Force -ErrorAction Stop
    Write-Host "OK -> $pluginDir\LiftoffFpvGoggles.dll" -ForegroundColor Green
}
catch {
    Write-Host "Compiled to $outDll" -ForegroundColor Green
    Write-Host "Could not install - is the game still running? Run build.ps1 again after closing it." -ForegroundColor Yellow
    exit 2
}
